from typing import List, Optional
from ..domain.models import PriceRecord, FacilitiesSummary, WeightsProfile, NeighbourhoodScore

class IPriceRepo:
    def series(self, area_id: str, months: int) -> List[PriceRecord]: ...

class IAmenityRepo:
    def facilities_summary(self, area_id: str) -> FacilitiesSummary: ...

class ICommunityRepo:
    """Repository interface for community centres"""
    def list_all(self) -> List[str]: ...  # return list of areaIds that have a community centre
    def exists(self, area_id: str) -> bool: ...

class IWeightsRepo:
    def get_active(self) -> WeightsProfile: ...
    def list(self) -> List[WeightsProfile]: ...
    def save(self, p: WeightsProfile) -> None: ...

class IScoreRepo:
    def latest(self, area_id: str, weights_id: str) -> Optional[NeighbourhoodScore]: ...
    def save(self, s: NeighbourhoodScore) -> None: ...